#!/usr/bin/env python3
import os
import tempfile
from importlib.machinery import SourceFileLoader
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = SourceFileLoader("schema", str(ROOT / "scripts" / "schema")).load_module()
HOT = SourceFileLoader("hotkeys", str(ROOT / "scripts" / "hotkeys")).load_module()
GEOM = SourceFileLoader("geom", str(ROOT / "scripts" / "geom")).load_module()
MATCH = SourceFileLoader("match", str(ROOT / "scripts" / "match")).load_module()
G = SourceFileLoader("gestures", str(ROOT / "scripts" / "gestures")).load_module()


def test_normalize_chord():
    assert SCHEMA.normalize_chord("SUPER + SHIFT + 2") == "SUPER + SHIFT + 2"
    assert SCHEMA.normalize_chord("super+shift+2") == "SUPER + SHIFT + 2"
    assert SCHEMA.normalize_chord("META + A") == "SUPER + A"
    assert SCHEMA.normalize_chord("CTRL + ALT + RETURN") == "CTRL + ALT + RETURN"
    assert SCHEMA.normalize_chord("SHIFT + A") == ""
    assert SCHEMA.normalize_chord("A") == ""
    assert SCHEMA.normalize_chord("SUPER + SHIFT + 2; os.execute") == ""
    assert SCHEMA.normalize_chord('SUPER + "A"') == ""
    assert SCHEMA.normalize_chord("SUPER + period") == "SUPER + period"
    assert SCHEMA.normalize_chord("SUPER + F12") == "SUPER + F12"
    assert SCHEMA.normalize_chord("SUPER + F13") == ""
    assert SCHEMA.normalize_chord("") == ""


def test_duplicate_chords_prefer_globals():
    hot = SCHEMA.normalize_hotkeys({
        "applyMatching": "SUPER + ALT + W",
        "applyFresh": "SUPER + ALT + W",
        "workspaces": {"2": "SUPER + ALT + W", "3": "SUPER + SHIFT + 3"},
    })
    assert hot["applyMatching"] == "SUPER + ALT + W"
    assert hot["applyFresh"] == ""
    assert "2" not in hot["workspaces"]
    assert hot["workspaces"]["3"] == "SUPER + SHIFT + 3"


def test_render_lua_allowlisted():
    cfg = {
        "settings": {
            "hotkeys": {
                "applyMatching": "SUPER + ALT + W",
                "applyFresh": "SUPER + ALT + SHIFT + W",
                "workspaces": {"2": "SUPER + SHIFT + 2"},
            }
        }
    }
    lua = HOT.render_lua(HOT.collect_binds(cfg, str(ROOT)), [])
    assert "-- Generated by WorkScape. Do not edit." in lua
    assert 'hl.unbind("SUPER + ALT + W")' in lua
    assert 'o.bind("SUPER + ALT + W", "WorkScape: apply matching"' in lua
    assert "--apply-matching" in lua
    assert "--fresh-apply-profile" in lua
    assert "--apply-workspace-here 2" in lua
    assert "os.execute" not in lua
    assert "bash -c" not in lua
    assert "workscape.sh" in lua


def test_render_unbinds_removed_chords():
    cfg = {"settings": {"hotkeys": {}}}
    lua = HOT.render_lua(HOT.collect_binds(cfg, str(ROOT)), ["SUPER + SHIFT + 2"])
    assert 'hl.unbind("SUPER + SHIFT + 2")' in lua
    assert "o.bind(" not in lua


def test_injection_dropped_from_binds():
    cfg = {
        "settings": {
            "hotkeys": {
                "applyMatching": 'SUPER + A")\nos.execute("rm")\n--',
                "workspaces": {"2": "SUPER + SHIFT + 2"},
            }
        }
    }
    binds = HOT.collect_binds(cfg, str(ROOT))
    chords = [b["chord"] for b in binds]
    assert "SUPER + SHIFT + 2" in chords
    assert all("os.execute" not in b["chord"] for b in binds)
    lua = HOT.render_lua(binds, [])
    assert "os.execute" not in lua


def test_remap_profile_workspace():
    profile = {
        "id": "p",
        "assignments": [
            {"workspace": 2, "exec": "foot", "enabled": True, "geom": {"x": 0, "y": 0, "w": 0.5, "h": 1}},
            {"workspace": 3, "exec": "brave", "enabled": True},
        ],
        "workspacePrefs": {"2": {"layout": "scrolling", "visibleCount": 3}},
        "workspaceMonitors": {"2": "desk-left"},
    }
    out = GEOM.remap_profile_workspace(profile, "2", "8")
    assert len(out["assignments"]) == 1
    assert out["assignments"][0]["workspace"] == 8
    assert out["assignments"][0]["exec"] == "foot"
    assert out["workspacePrefs"]["8"]["layout"] == "scrolling"
    assert out["workspaceMonitors"] == {}
    assert profile["assignments"][0]["workspace"] == 2


def test_workspace_pref_luas_scrolling():
    cmds = MATCH.workspace_pref_luas("8", "scrolling", 2, False, "")
    joined = "\n".join(cmds)
    assert 'workspace = "8"' in joined
    assert "scrolling" in joined
    assert "column_width" in joined
    assert "monitor =" not in joined


def test_write_inserts_hotkeys_require():
    tmp_path = Path(tempfile.mkdtemp(prefix="workscape-hotkeys-"))
    os.environ["WORKSCAPE_STATE_DIR"] = str(tmp_path / "state")
    (tmp_path / "state").mkdir()
    hypr = tmp_path / "hypr"
    hypr.mkdir()
    (hypr / "hyprland.lua").write_text("-- user hyprland\n")
    cfg = {"settings": {"hotkeys": {"applyMatching": "SUPER + ALT + W"}}}
    orig = G.hypr_eval
    G.hypr_eval = lambda lua: None
    HOT.GESTURES.hypr_eval = lambda lua: None
    try:
        out = HOT.write_and_apply(cfg, str(ROOT), str(hypr))
        assert out["ok"] is True
        text = (hypr / "workscape-hotkeys.lua").read_text()
        assert "apply matching" in text
        hyprland = (hypr / "hyprland.lua").read_text()
        assert 'pcall(require, "hypr.workscape-hotkeys")' in hyprland
        restored = G.restore_hypr_persist(str(hypr))
        assert restored["ok"] is True
        assert 'pcall(require, "hypr.workscape-hotkeys")' not in (hypr / "hyprland.lua").read_text()
        assert not (hypr / "workscape-hotkeys.lua").exists()
    finally:
        G.hypr_eval = orig
        HOT.GESTURES.hypr_eval = orig
        os.environ.pop("WORKSCAPE_STATE_DIR", None)


if __name__ == "__main__":
    test_normalize_chord()
    test_duplicate_chords_prefer_globals()
    test_render_lua_allowlisted()
    test_render_unbinds_removed_chords()
    test_injection_dropped_from_binds()
    test_remap_profile_workspace()
    test_workspace_pref_luas_scrolling()
    test_write_inserts_hotkeys_require()
    print("hotkeys.test.py ok")
